import type { Metadata } from "next";
import { Suspense } from "react";
import { Fredoka, Manrope } from "next/font/google";
import "./globals.css";
import Provider from "@/provider/provider";
import StorefrontFrame from "@/component/Layout/StorefrontFrame";

const manrope = Manrope({
  variable: "--font-body",
  subsets: ["latin"],
  display: "swap",
});

// Rounded display face for every heading level.
const fredoka = Fredoka({
  variable: "--font-heading",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "KOFORA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${manrope.variable} ${fredoka.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Provider>
          <Suspense fallback={<>{children}</>}>
            <StorefrontFrame>{children}</StorefrontFrame>
          </Suspense>
        </Provider>
      </body>
    </html>
  );
}
