import type { Metadata } from "next";
import { Suspense } from "react";
import { DM_Sans, Plus_Jakarta_Sans, Fraunces } from "next/font/google";
import "./globals.css";
import Provider from "@/provider/provider";
import StorefrontFrame from "@/component/Layout/StorefrontFrame";

const dmSans = DM_Sans({
  variable: "--font-body",
  subsets: ["latin"],
});

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-heading",
  subsets: ["latin"],
});

// Accent serif, used for the display headings on the marketing sections.
const fraunces = Fraunces({
  variable: "--font-accent",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "KOFORA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${dmSans.variable} ${plusJakartaSans.variable} ${fraunces.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Provider>
          <Suspense fallback={<>{children}</>}>
            <StorefrontFrame>{children}</StorefrontFrame>
          </Suspense>
        </Provider>
      </body>
    </html>
  );
}
