import type { Metadata } from "next";
import { DM_Sans, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Provider from "@/provider/provider";
import MainNavbar from "@/component/Navbar/Navbar";
import Footer from "@/component/Footer/Footer";
import DiscountPill from "@/ui/DiscountPill";
import AnnouncementBar from "@/component/Navbar/Annoucement";
import { CartDrawer } from "@/component/Cart/cartDrawer";
import ProductModal from "@/component/Product/ProductModal";

const dmSans = DM_Sans({
  variable: "--font-body",
  subsets: ["latin"],
});

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-heading",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "KOFORA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, 
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${dmSans.variable} ${plusJakartaSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Provider>
          <AnnouncementBar/>
          <MainNavbar/>
          <DiscountPill/> 
          {children}
          <Footer/>
          <ProductModal/>
          <CartDrawer/>
        </Provider>
        
      </body>
    </html>
  );
}
